"""
Django settings for company_backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zr^v_cr+gz9u4lx8xkhy9jie(lf!y)ayq8%dr7cd=n)%bo5)m8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Django REST Framework
    'corsheaders',     # CORS Headers
    'users',           # Custom app
    'rest_framework_simplejwt', 
    'sslserver','forging','import_export','heat_treatment','shot_blast','pre_mc','cnc','marking','visual','fi',
    'raw_material','costumer_complaint','calibration','other','simple_history','django_filters',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS Middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'company_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'company_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'testing',
        'USER': 'root',
        'PASSWORD': 'ENGeng#123',
        'HOST': 'localhost',  # Or the IP address of your MySQL server
        'PORT': '3306',       # Default MySQL port
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-in'

TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# settings.py
AUTH_USER_MODEL = 'users.CustomUser'

# remove this portion to access Django admin panel///////////////////////////////////////////////////////////////////////////////////////////////////

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    "http://localhost:5173",
    "http://192.168.1.199:5173",
    "http://192.168.1.199:5175",
    "http://192.168.1.199:8000",
    "http://192.168.1.199:5188",
]
# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # This allows all origins. In production, you should specify allowed origins.
# Alternatively, you can specify just the React app origin
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",  # React dev server
# ]

CORS_ALLOW_CREDENTIALS = True  # Allows cookies to be included in requests
CORS_ORIGIN_ALLOW_ALL = True  # Allow all origins (be cautious in production)

# CSRF settings
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",  # React dev server
    "http://127.0.0.1:8000",  # Django dev server
    "http://192.168.1.199:5173",
    "http://192.168.1.199:5175",
    "http://192.168.1.199:8001",
    "http://192.168.1.199:8000",
    "http://192.168.1.199:5188",
]

# Make sure CSRF cookies are set correctly for local development without HTTPS
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_SAMESITE = 'None'  # Important for cross-origin requests
CSRF_COOKIE_SECURE = False  # Set to True if your site uses HTTPS
CSRF_COOKIE_HTTPONLY = False  # Ensure the cookie is accessible to JavaScript

SESSION_COOKIE_SAMESITE = 'None'  # Important for cross-origin requests
SESSION_COOKIE_SECURE = False  # Set to True if your site uses HTTPS

# If using JWT, you might also want to ensure the settings are correct
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1220),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=5),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

# remove this portion to access Django admin panel///////////////////////////////////////////////////////////////////////////////////////////////////