# Generated by Django 5.1.4 on 2025-02-10 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('complaint_date', models.DateField()),
                ('target_submission_date', models.DateField()),
                ('part_number', models.CharField(max_length=255)),
                ('phenomena', models.TextField()),
                ('complaint_description', models.TextField()),
                ('is_repeated', models.BooleanField(default=False)),
                ('invoice_batch_no', models.CharField(max_length=255)),
                ('lot_size', models.IntegerField()),
                ('rejection_qty', models.IntegerField()),
                ('interim_action', models.TextField()),
                ('root_cause', models.TextField()),
                ('corrective_action', models.TextField()),
                ('documents_revised', models.TextField(blank=True, null=True)),
                ('action_complaint_date', models.DateField(blank=True, null=True)),
                ('capa_submission_date', models.DateField(blank=True, null=True)),
                ('effectiveness_review', models.TextField(blank=True, null=True)),
                ('completion_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_changed', models.CharField(max_length=255)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='costumer_complaint.complaint')),
            ],
        ),
    ]
