# Generated by Django 5.1.4 on 2025-02-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer_complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='avidancefile',
            field=models.FileField(blank=True, upload_to='complaint_documents/avidancefile/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaintfile',
            field=models.FileField(blank=True, upload_to='complaint_documents/complaintfile/'),
        ),
    ]
