# Generated by Django 5.1.4 on 2025-02-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer_complaint', '0002_complaint_avidancefile_complaint_complaintfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainthistory',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complainthistory',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
