# Generated by Django 5.1.4 on 2025-01-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marking',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
    ]
