# Generated by Django 5.1.4 on 2024-12-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pre_mc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('heat_no', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('shop_floor', models.CharField(choices=[('Hi-Tech', 'Hi-Tech'), ('Manya', 'Manya'), ('In-House', 'In-House')], max_length=50)),
                ('target', models.IntegerField()),
                ('total_produced', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('verified_by', models.CharField(max_length=100)),
            ],
        ),
    ]
