# Generated by Django 5.1.4 on 2025-01-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_mc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_mc',
            name='remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pre_mc',
            name='shop_floor',
            field=models.CharField(max_length=50),
        ),
    ]
