# Generated by Django 5.1.4 on 2025-01-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heattreatment',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
    ]
