# Generated by Django 5.1.4 on 2024-12-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('Admin', 'Admin'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing')], default='IT', max_length=100),
        ),
    ]
