# Generated by Django 5.1.4 on 2025-01-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('Admin', 'Admin'), ('Rm', 'Rm'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('DepartmentPage', 'DepartmentPage')], default='IT', max_length=100),
        ),
    ]
