# Generated by Django 5.1.4 on 2025-02-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('Admin', 'Admin'), ('qa', 'qa'), ('Forging', 'Forging'), ('pre_mc', 'pre_mc'), ('ht', 'ht'), ('Rm', 'Rm'), ('visual', 'visual'), ('fi', 'fi'), ('cnc', 'cnc'), ('marking', 'marking'), ('shot_blast', 'shot_blast'), ('dispatch', 'dispatch'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('DepartmentPage', 'DepartmentPage')], default='DepartmentPage', max_length=100),
        ),
    ]
