# Generated by Django 5.1.4 on 2025-01-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_mt_id', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('customer', models.CharField(max_length=100)),
                ('standerd', models.CharField(max_length=100)),
                ('component_no', models.CharField(max_length=100)),
                ('material_grade', models.CharField(max_length=100)),
                ('bardia', models.CharField(max_length=100)),
                ('heat_no', models.CharField(max_length=100)),
                ('rack_no', models.CharField(max_length=100)),
                ('bar_qty', models.CharField(max_length=100)),
                ('kg_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Blockmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_mt_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('component', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('standerd', models.CharField(max_length=100)),
                ('heatno', models.CharField(max_length=50)),
                ('dia', models.CharField(max_length=100)),
                ('rack_no', models.CharField(max_length=50)),
                ('pices', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('supplier', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=100)),
                ('standerd', models.CharField(max_length=100)),
                ('heatno', models.CharField(max_length=50)),
                ('dia', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rack_no', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('type_of_material', models.CharField(max_length=100)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_no', models.CharField(max_length=50)),
                ('milltc', models.FileField(blank=True, null=True, upload_to='reports/MILLTC')),
                ('spectro', models.FileField(blank=True, null=True, upload_to='reports/SPECTRO')),
                ('ssb_inspection_report', models.FileField(blank=True, null=True, upload_to='reports/SSBINSPECTION')),
                ('verified_by', models.CharField(blank=True, max_length=150)),
                ('approval_status', models.CharField(blank=True, choices=[('Under Inspection', 'Under Inspection'), ('Hold', 'Hold'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Under Inspection', max_length=20, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
