# Generated by Django 5.1.4 on 2025-01-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0002_customer_grade_materialtype_supplier_typeofmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rmreciveinbatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_mt_id', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('heatno', models.CharField(max_length=50)),
                ('dia', models.CharField(max_length=100)),
                ('pcs', models.IntegerField()),
                ('rack_no', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
