# Generated by Django 5.1.4 on 2025-01-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0003_rmreciveinbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masterlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('drawing_number', models.IntegerField()),
                ('standerd', models.CharField(max_length=100)),
                ('material_grade', models.CharField(max_length=100)),
                ('slug_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bar_dia', models.CharField(max_length=100)),
                ('ring_weight', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
