# Generated by Django 5.1.4 on 2025-01-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0004_masterlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('standerd', models.CharField(blank=True, max_length=100)),
                ('dia', models.CharField(max_length=100)),
                ('slug_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pices', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date1', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('verified_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
