# Generated by Django 5.1.4 on 2025-01-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0005_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('component', models.CharField(max_length=100)),
                ('pices', models.IntegerField()),
                ('invoiceno', models.CharField(max_length=100)),
                ('addpdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('heat_no', models.CharField(max_length=100)),
                ('target1', models.IntegerField()),
                ('total_produced', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('batch_number', models.CharField(max_length=50)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
