# Generated by Django 5.1.4 on 2025-01-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0006_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='target1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='total_produced',
            field=models.IntegerField(default=0),
        ),
    ]
