# Generated by Django 5.1.4 on 2025-01-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0007_masterlist_cost_alter_dispatch_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='component_cycle_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
