# Generated by Django 5.1.4 on 2025-01-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0008_masterlist_component_cycle_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('Under Inspection', 'Under Inspection'), ('Hold', 'Hold'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default=None, max_length=20, null=True),
        ),
    ]
