# Generated by Django 5.1.4 on 2025-02-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0009_alter_rawmaterial_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='comments',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
