# Generated by Django 5.1.4 on 2025-02-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0011_alter_rawmaterial_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='comments',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
