# Generated by Django 5.1.4 on 2025-02-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0012_alter_rawmaterial_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='process',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
