# Generated by Django 5.1.4 on 2025-03-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0013_masterlist_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='delivery_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
