# Generated by Django 5.1.4 on 2025-03-07 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0014_supplier_delivery_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_grade', models.CharField(max_length=100)),
                ('rm_standard', models.CharField(max_length=100)),
                ('bar_dia', models.FloatField()),
                ('qty', models.IntegerField()),
                ('po_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('delay_days', models.IntegerField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_material.supplier')),
            ],
        ),
    ]
