# Generated by Django 5.1.4 on 2025-03-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0015_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='heat_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
