# Generated by Django 5.1.4 on 2025-03-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0016_order_heat_no_order_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlist',
            name='cnc_target_remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='op_10_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='op_10_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='op_20_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='op_20_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
