# Generated by Django 5.1.4 on 2025-03-10 06:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0017_masterlist_cnc_target_remark_masterlist_op_10_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMasterlist',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('drawing_number', models.IntegerField()),
                ('standerd', models.CharField(max_length=100)),
                ('material_grade', models.CharField(max_length=100)),
                ('slug_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bar_dia', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=100)),
                ('ring_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('component_cycle_time', models.IntegerField()),
                ('op_10_time', models.IntegerField(blank=True, null=True)),
                ('op_10_target', models.IntegerField(blank=True, null=True)),
                ('op_20_time', models.IntegerField(blank=True, null=True)),
                ('op_20_target', models.IntegerField(blank=True, null=True)),
                ('cnc_target_remark', models.CharField(blank=True, max_length=500, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical masterlist',
                'verbose_name_plural': 'historical masterlists',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
