# Generated by Django 5.1.4 on 2025-03-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0019_purchaseorder_order_description_of_good_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255)),
                ('heat', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('complaint_date', models.DateField()),
                ('issue', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['supplier'], name='raw_materia_supplie_543c9d_idx'), models.Index(fields=['heat'], name='raw_materia_heat_4be114_idx'), models.Index(fields=['grade'], name='raw_materia_grade_7db320_idx'), models.Index(fields=['complaint_date'], name='raw_materia_complai_15759e_idx')],
            },
        ),
    ]
