# Generated by Django 5.1.4 on 2025-03-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0020_materialcomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcomplaint',
            name='component',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialcomplaint',
            name='verified_by',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
