# Generated by Django 5.1.4 on 2025-03-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0021_materialcomplaint_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcomplaint',
            name='pices',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
