# Generated by Django 5.1.4 on 2025-03-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0022_materialcomplaint_pices'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcomplaint',
            name='Complaint_photo',
            field=models.FileField(blank=True, null=True, upload_to='RmComplaint/Complaint_photo'),
        ),
        migrations.AddField(
            model_name='materialcomplaint',
            name='d8_report',
            field=models.FileField(blank=True, null=True, upload_to='RmComplaint/d8_report'),
        ),
    ]
