# Generated by Django 5.1.4 on 2025-03-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0023_materialcomplaint_complaint_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcomplaint',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
