# Generated by Django 5.1.4 on 2025-03-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0024_materialcomplaint_closing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcomplaint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
    ]
