# Generated by Django 5.1.4 on 2025-03-27 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0025_materialcomplaint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAuditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('audit_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_material.supplier')),
            ],
            options={
                'indexes': [models.Index(fields=['supplier', 'month'], name='raw_materia_supplie_d5bb29_idx')],
                'unique_together': {('supplier', 'month')},
            },
        ),
    ]
