# Generated by Django 5.1.4 on 2025-03-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0026_supplierauditscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
