# Generated by Django 5.1.4 on 2025-03-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0027_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_gstin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
