# Generated by Django 5.1.4 on 2025-03-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0028_supplier_supplier_details_supplier_supplier_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approval_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='approval_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
