# Generated by Django 5.1.4 on 2025-03-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0029_order_approval_status_order_approval_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
    ]
