# Generated by Django 5.1.4 on 2025-03-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0031_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
