# Generated by Django 5.1.4 on 2025-03-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0032_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completion_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
