# Generated by Django 5.1.4 on 2025-04-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0035_order_force_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_terms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
