# Generated by Django 5.1.4 on 2025-04-15 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0037_historicalmasterlistdocument_masterlistdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmasterlist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 15, 8, 56, 12, 386631, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 15, 8, 56, 51, 986358, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
