# Generated by Django 5.1.4 on 2025-04-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0038_historicalmasterlist_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmasterlistdocument',
            name='document_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='masterlistdocument',
            name='document_type',
            field=models.CharField(max_length=50),
        ),
    ]
