# Generated by Django 5.1.4 on 2025-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0039_order_manual_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manual_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
