# Generated by Django 5.1.4 on 2025-04-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0041_order_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmasterlist',
            old_name='process',
            new_name='ht_process',
        ),
        migrations.RenameField(
            model_name='masterlist',
            old_name='process',
            new_name='ht_process',
        ),
        migrations.AddField(
            model_name='historicalmasterlist',
            name='drawing_rev_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlist',
            name='drawing_rev_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlist',
            name='hardness_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlist',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlist',
            name='packing_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlist',
            name='running_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlist',
            name='verified_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalmasterlistdocument',
            name='verified_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='drawing_rev_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='drawing_rev_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='hardness_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='packing_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='running_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='verified_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='masterlistdocument',
            name='verified_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
