# Generated by Django 5.1.4 on 2025-04-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0042_rename_process_historicalmasterlist_ht_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmasterlist',
            name='forging_line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='forging_line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
