# Generated by Django 5.1.4 on 2025-02-13 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CALIBRATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_instrument', models.CharField(blank=True, max_length=100)),
                ('uid', models.CharField(blank=True, max_length=100, unique=True)),
                ('catagory', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('CALIBRATION_AGENCY', models.CharField(blank=True, max_length=100, null=True)),
                ('CALIBRATION_DONE_DATE', models.CharField(blank=True, max_length=100, null=True)),
                ('DUE_DAYS', models.CharField(blank=True, max_length=100, null=True)),
                ('RANGE', models.CharField(blank=True, max_length=100, null=True)),
                ('LEAST_COUNT', models.CharField(blank=True, max_length=100, null=True)),
                ('LOCATION', models.CharField(blank=True, max_length=50, null=True)),
                ('component', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('add_pdf', models.FileField(blank=True, null=True, upload_to='calibration_certificate/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CALIBRATIONHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_changed', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='calibration.calibration')),
            ],
        ),
    ]
