# Generated by Django 5.1.4 on 2025-02-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibration',
            old_name='DUE_DAYS',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='calibration',
            name='po_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
