# Generated by Django 5.1.4 on 2025-02-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_rename_due_days_calibration_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('receiving_status', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
