# Generated by Django 5.1.4 on 2025-02-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='receiving_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
