# Generated by Django 5.1.4 on 2025-03-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0005_calibration_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='id',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='id',
            name='name_of_instrument',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='id',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
