# Generated by Django 5.1.4 on 2024-12-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('slug_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rm_grade', models.CharField(max_length=100)),
                ('heat_number', models.CharField(max_length=100)),
                ('line', models.CharField(max_length=100)),
                ('line_incharge', models.CharField(max_length=100)),
                ('forman', models.CharField(max_length=100)),
                ('target', models.IntegerField()),
                ('production', models.IntegerField()),
                ('rework', models.IntegerField()),
                ('up_setting', models.IntegerField()),
                ('half_piercing', models.IntegerField()),
                ('full_piercing', models.IntegerField()),
                ('ring_rolling', models.IntegerField()),
                ('sizing', models.IntegerField()),
                ('overheat', models.IntegerField()),
                ('bar_crack_pcs', models.IntegerField()),
                ('verified_by', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
