# Generated by Django 5.1.4 on 2025-01-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0002_alter_machining_remaining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cncplanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cnc_uid', models.CharField(max_length=150, unique=True)),
                ('create_date', models.DateField()),
                ('Target_start_date', models.DateField()),
                ('Target_End_date', models.DateField()),
                ('component', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('target', models.IntegerField()),
                ('component_cycle_time', models.IntegerField()),
                ('required_cycle_time', models.IntegerField()),
                ('cell', models.CharField(max_length=100)),
                ('cell_cycle_time', models.IntegerField()),
                ('done', models.CharField(blank=True, max_length=100)),
                ('how_much_compleate', models.IntegerField(blank=True)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
