# Generated by Django 5.1.4 on 2025-01-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0003_cncplanning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnc_line_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=50)),
                ('cell', models.DateField()),
                ('cell_cycle_time', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cncplanning',
            name='cnc_line',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
