# Generated by Django 5.1.4 on 2025-01-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0004_cnc_line_master_cncplanning_cnc_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='cncplanning',
            name='done_marked_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
