# Generated by Django 5.1.4 on 2025-01-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0005_cncplanning_done_marked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cncplanning',
            name='machine_cycle_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cncplanning',
            name='machine_no',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
