# Generated by Django 5.1.4 on 2025-01-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0006_cncplanning_machine_cycle_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cncplanning',
            name='cell',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cncplanning',
            name='cell_cycle_time',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cncplanning',
            name='machine_cycle_time',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cncplanning',
            name='machine_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
