# Generated by Django 5.1.4 on 2025-02-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0009_cnc_line_master_runningstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnc_line_master',
            name='remark',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
