# Generated by Django 5.1.4 on 2025-02-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0010_cnc_line_master_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnc_line_master',
            name='machine_no',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
